### ISSUE TITLE
traceback

### ISSUE THREAD

**Issue by Typohannes** [Typefounding/copyGlyphs#1]
Heya Ben, I tried this extension and here is the traceback I get when I run it:

Traceback (most recent call last):
  File "copy_glyphs.py", line 103, in <module>
  File "lib/scripting/nameSpaceCallbacks.pyc", line 206, in OpenWindow
  File "copy_glyphs.py", line 24, in __init__
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by benkiel** [comment]
Hannes, did one of your fonts not have a family or style name?

**Comment by benkiel** [comment]
Actually, pretty sure that was it. Added some checking in https://github.com/Typefounding/copyGlyphs/commit/e756a760fbb7084305b66c0e284e5bd306d5aafb

**Comment by Typohannes** [comment]
Yes Ben, the fonts had family names but no style names. Thanks for looking into this!
